import { Doctor, HealthIssue, TimeSlot } from '../types';

export const healthIssues: HealthIssue[] = [
  { id: 'fever', name: 'Fever & Care', icon: 'thermometer-outline' },
  { id: 'checkup', name: 'General Checkup', icon: 'medkit-outline' },
  { id: 'nursing', name: 'Home Nursing', icon: 'bandage-outline' },
  { id: 'elderly', name: 'Senior Care', icon: 'accessibility-outline' },
  { id: 'pediatric', name: 'Kids Health', icon: 'happy-outline' },
  { id: 'injections', name: 'Injections & IV', icon: 'flask-outline' },
  { id: 'diabetes', name: 'Diabetes Care', icon: 'water-outline' },
  { id: 'skin', name: 'Skin Care', icon: 'sparkles-outline' },
];

const slots = (labels: string[]): TimeSlot[] => labels.map((label, index) => ({ id: `${index}-${label}`, label, available: true }));
export const getDateKey = (offset: number) => { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().split('T')[0]; };

export const doctors: Doctor[] = [
  { id: 'nurse-kavita', name: 'Nurse Kavitha Sharma', specialty: 'Senior Home Care Nurse (B.Sc Nursing)', hospital: 'Apollo Home Care', location: 'Banjara Hills', rating: 4.9, experience: 10, fee: 500, phone: '+919876543230', initials: 'KS', avatar: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=200&auto=format&fit=crop&q=80', issueIds: ['nursing', 'elderly', 'checkup', 'injections'], symptoms: ['nurse', 'nursing', 'elderly care', 'bedridden', 'vital check', 'catheter', 'home care', 'injections', 'blood pressure'], slots: {} },
  { id: 'nurse-rajesh', name: 'Nurse Rajesh Verma', specialty: 'ICU & Critical Care Nurse', hospital: 'KIMS Home Health', location: 'Jubilee Hills', rating: 4.8, experience: 8, fee: 450, phone: '+919876543231', initials: 'RV', avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&auto=format&fit=crop&q=80', issueIds: ['nursing', 'fever', 'checkup', 'injections'], symptoms: ['nurse', 'nursing', 'icu care', 'critical', 'oxygen', 'nebulization', 'injections', 'fever', 'emergency care', 'drip'], slots: {} },
  { id: 'nurse-sunita', name: 'Nurse Sunita Rao', specialty: 'Elderly & Post-Op Recovery Nurse', hospital: 'MaxCare Home Nursing', location: 'Madhapur', rating: 4.95, experience: 12, fee: 600, phone: '+919876543232', initials: 'SR', avatar: 'https://images.unsplash.com/photo-1594824813566-88855ce78907?w=200&auto=format&fit=crop&q=80', issueIds: ['nursing', 'elderly'], symptoms: ['nurse', 'nursing', 'post surgery', 'post op recovery', 'wound care', 'elderly', 'paralysis care', 'dressing'], slots: {} },
  { id: 'nurse-deepa', name: 'Nurse Deepa Verma', specialty: 'Injection & Dressing Care Nurse', hospital: 'Care Home Services', location: 'Gachibowli', rating: 4.7, experience: 7, fee: 400, phone: '+919876543233', initials: 'DV', avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200&auto=format&fit=crop&q=80', issueIds: ['nursing', 'fever', 'injections'], symptoms: ['nurse', 'nursing', 'injection', 'iv drip', 'blood test', 'sample collection', 'dressing', 'wound dressing'], slots: {} },
  { id: 'ananya', name: 'Dr. Ananya Sharma', specialty: 'General Physician', hospital: 'Apollo Hospitals', location: 'Banjara Hills', rating: 4.9, experience: 12, fee: 850, phone: '+919876543210', initials: 'AS', avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&auto=format&fit=crop&q=80', issueIds: ['fever', 'checkup', 'diabetes'], symptoms: ['fever', 'headache', 'cold', 'cough', 'viral', 'flu', 'body pain', 'vomiting', 'fatigue', 'weakness', 'chills', 'infection', 'throat pain'], slots: {} },
  { id: 'rohan', name: 'Dr. Rohan Mehta', specialty: 'Family Medicine', hospital: 'KIMS Hospitals', location: 'Jubilee Hills', rating: 4.8, experience: 9, fee: 700, phone: '+919876543211', initials: 'RM', avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup', 'elderly', 'fever'], symptoms: ['fever', 'stomach ache', 'headache', 'diarrhea', 'gas', 'acidity', 'body ache', 'checkup', 'weakness', 'cough', 'cold'], slots: {} },
  { id: 'priya', name: 'Dr. Priya Iyer', specialty: 'Pediatrician', hospital: "Rainbow Children's Hospital", location: 'Madhapur', rating: 4.7, experience: 8, fee: 900, phone: '+919876543212', initials: 'PI', avatar: 'https://images.unsplash.com/photo-1594824813566-88855ce78907?w=200&auto=format&fit=crop&q=80', issueIds: ['pediatric', 'fever'], symptoms: ['child fever', 'baby cough', 'pediatric', 'kids cold', 'vaccination', 'child vomit', 'infant care', 'growth', 'baby rash', 'child'], slots: {} },
  { id: 'kabir', name: 'Dr. Kabir Singh', specialty: 'Internal Medicine', hospital: 'MaxCure Hospitals', location: 'Kondapur', rating: 4.6, experience: 15, fee: 1000, phone: '+919876543213', initials: 'KS', avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&auto=format&fit=crop&q=80', issueIds: ['diabetes', 'elderly', 'checkup'], symptoms: ['diabetes', 'sugar', 'high bp', 'blood pressure', 'thyroid', 'cholesterol', 'chest tightness', 'general weakness', 'kidney care'], slots: {} },
  { id: 'meera', name: 'Dr. Meera Nair', specialty: 'Cardiologist', hospital: 'Continental Hospitals', location: 'Gachibowli', rating: 4.9, experience: 14, fee: 1200, phone: '+919876543214', initials: 'MN', avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup', 'diabetes'], symptoms: ['chest pain', 'heart', 'palpitations', 'high bp', 'shortness of breath', 'cardiac', 'dizziness', 'chest discomfort', 'heart attack'], slots: {} },
  { id: 'aditi', name: 'Dr. Aditi Kapoor', specialty: 'Gynecologist', hospital: 'Care Hospitals', location: 'Hitech City', rating: 4.8, experience: 11, fee: 1100, phone: '+919876543215', initials: 'AK', avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup'], symptoms: ['pregnancy', 'period pain', 'menstrual', 'pcos', 'pcod', 'women health', 'abdominal pain', 'pregnancy checkup', 'gynae'], slots: {} },
  { id: 'vikram', name: 'Dr. Vikram Rao', specialty: 'Psychiatrist', hospital: 'Yashoda Hospitals', location: 'Somajiguda', rating: 4.7, experience: 10, fee: 1000, phone: '+919876543216', initials: 'VR', avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup'], symptoms: ['anxiety', 'depression', 'stress', 'insomnia', 'sleep disorder', 'panic', 'mental health', 'mood swings', 'psychiatry'], slots: {} },
  { id: 'neel', name: 'Dr. Neel Joshi', specialty: 'Orthopedist', hospital: 'Sunshine Hospitals', location: 'Secunderabad', rating: 4.8, experience: 13, fee: 1050, phone: '+919876543217', initials: 'NJ', avatar: 'https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=200&auto=format&fit=crop&q=80', issueIds: ['elderly'], symptoms: ['back pain', 'joint pain', 'knee pain', 'bone fracture', 'arthritis', 'cramps', 'neck pain', 'shoulder pain', 'spine'], slots: {} },
  { id: 'sana', name: 'Dr. Sana Khan', specialty: 'Dermatologist', hospital: 'DermaClinics Center', location: 'Kukatpally', rating: 4.7, experience: 9, fee: 950, phone: '+919876543218', initials: 'SK', avatar: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=200&auto=format&fit=crop&q=80', issueIds: ['skin'], symptoms: ['skin rash', 'acne', 'pimples', 'itching', 'hair loss', 'fungal infection', 'dandruff', 'allergy', 'eczema', 'skin'], slots: {} },
  { id: 'arjun', name: 'Dr. Arjun Menon', specialty: 'Neurologist', hospital: 'Star Hospitals', location: 'Begumpet', rating: 4.6, experience: 16, fee: 1300, phone: '+919876543219', initials: 'AM', avatar: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup'], symptoms: ['migraine', 'severe headache', 'paralysis', 'seizure', 'fits', 'numbness', 'nerve pain', 'dizziness', 'memory loss'], slots: {} },
  { id: 'isha', name: 'Dr. Isha Bansal', specialty: 'Dentist', hospital: 'Clove Dental Care', location: 'Ameerpet', rating: 4.8, experience: 8, fee: 700, phone: '+919876543220', initials: 'IB', avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup'], symptoms: ['toothache', 'teeth pain', 'bleeding gums', 'cavity', 'wisdom tooth', 'dental', 'mouth ulcer', 'root canal', 'teeth'], slots: {} },
  { id: 'rohit', name: 'Dr. Rohit Das', specialty: 'Ophthalmologist', hospital: 'LV Prasad Eye Institute', location: 'Manikonda', rating: 4.7, experience: 12, fee: 900, phone: '+919876543221', initials: 'RD', avatar: 'https://images.unsplash.com/photo-1637059824899-a441006a6875?w=200&auto=format&fit=crop&q=80', issueIds: ['checkup'], symptoms: ['eye pain', 'blurry vision', 'red eye', 'eye infection', 'cataract', 'spectacles', 'dry eyes', 'burning eye', 'eye'], slots: {} },
];
doctors.forEach((doctor) => [0, 1, 2, 3].forEach((offset) => { doctor.slots[getDateKey(offset)] = slots(offset === 0 ? ['10:00 AM', '12:30 PM', '04:00 PM'] : ['09:30 AM', '11:00 AM', '02:30 PM', '05:30 PM']); }));