import { Ionicons } from '@expo/vector-icons';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, Header, PrimaryButton } from '../components/UI';
import { useBooking } from '../context/BookingContext';
import { PaymentMode, RootStackParamList } from '../types';
type Props = NativeStackScreenProps<RootStackParamList, 'Payment'>;
export function PaymentScreen({ navigation }: Props) { const { selectedDoctor, choosePayment, confirmBooking } = useBooking(); const [mode, setMode] = useState<PaymentMode>('UPI'); const fee = selectedDoctor?.fee ?? 0; const choose = (item: PaymentMode) => { setMode(item); choosePayment(item); }; return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Header title="Payment & billing" onBack={() => navigation.goBack()} /><Text style={styles.lead}>Your visit is almost booked.</Text><View style={styles.summary}><View style={styles.summaryRow}><Text style={styles.muted}>Doctor consultation fee</Text><Text style={styles.value}>₹{fee}</Text></View><View style={styles.summaryRow}><Text style={styles.muted}>Platform fee</Text><Text style={styles.value}>₹50</Text></View><View style={styles.line} /><View style={styles.summaryRow}><Text style={styles.totalLabel}>Total amount due</Text><Text style={styles.total}>₹{fee + 50}</Text></View></View><Text style={styles.title}>Payment mode</Text>{(['UPI', 'Card', 'Cash on Visit'] as PaymentMode[]).map((item) => <Pressable key={item} onPress={() => choose(item)} style={[styles.mode, mode === item && styles.modeActive]}><View style={styles.modeIcon}><Ionicons name={item === 'UPI' ? 'phone-portrait-outline' : item === 'Card' ? 'card-outline' : 'cash-outline'} size={20} color={colors.green} /></View><Text style={styles.modeText}>{item}</Text><View style={[styles.radio, mode === item && styles.radioActive]} /></Pressable>)}<Text style={styles.note}>You will pay after confirming your appointment. A home visit usually takes 30–45 minutes.</Text><PrimaryButton title="Confirm booking" onPress={() => { choosePayment(mode); confirmBooking(mode); navigation.navigate('Confirmation'); }} /></ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.white }, container: { padding: 22 }, lead: { color: colors.muted, marginBottom: 22 }, summary: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 18 }, summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 7 }, muted: { color: colors.muted }, value: { color: colors.ink, fontWeight: '700' }, line: { height: 1, backgroundColor: colors.border, marginVertical: 10 }, totalLabel: { color: colors.ink, fontWeight: '800', fontSize: 16 }, total: { color: colors.green, fontWeight: '800', fontSize: 19 }, title: { color: colors.ink, fontSize: 18, fontWeight: '800', marginTop: 30, marginBottom: 14 }, mode: { borderWidth: 1, borderColor: colors.border, borderRadius: 12, flexDirection: 'row', alignItems: 'center', padding: 13, marginBottom: 10 }, modeActive: { borderColor: colors.green, backgroundColor: colors.soft }, modeIcon: { width: 38, height: 38, borderRadius: 10, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, modeText: { flex: 1, color: colors.ink, fontWeight: '700', marginLeft: 12 }, radio: { width: 19, height: 19, borderRadius: 10, borderWidth: 1, borderColor: '#AAA' }, radioActive: { borderWidth: 5, borderColor: colors.green }, note: { color: colors.muted, fontSize: 12, lineHeight: 18, marginVertical: 20 } });